title: BryTech
default_lang: en
author:
  name: 'Dave Bry'
  email: null
taxonomies:
  - category
  - tag
metadata:
  description: 'Seasoned .NET developer bringing 15+ years of unique experience from a variety of industries. With a history of solving complex problems and delivering innovative solutions, I have increased sales at Traffic Safety Store 20+% year-over-year, and saved Dechert LLP over $20,000/year. I am adaptable, open to change, and quick to learn in new situations. I possess Sherlock-like investigative skills to get to the root cause of technical issues.'
  generator: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
header_title: '&lt;brytech /&gt;'
copyright:
  copy:
    line: '&copy; Dave Bry 2021'
css_version: 1644774078
